# Generated by Django 5.1.2 on 2024-10-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_item_category_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
